#!/bin/sh

## read Xresources - not sure if this is necessary but whatever
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

## system settings
# turn on/off system beep
xset b off &


## pointer settings
# mouse acceleration - accel ratio and threshold
xset m 1/1 0 &

# touchpad settings
if egrep -iq 'synap|alps|etps' /proc/bus/input/devices; then
	synclient AccelFactor=0
	synclient MinSpeed=1.25
	synclient MaxSpeed=3
	# tapping the touchpad sends a mouse button 1 event
	synclient TapButton1=1
fi


## keyboard settings
# keyboard repeat - delay (ms) and characters per second
xset r rate 175 35 &

# set the compose key
setxkbmap -option compose:ralt &


## start applications
if command -v xflux >/dev/null 2>&1; then
	xflux -l 58 -g 5 -k 2900 &
fi

if command -v dropbox >/dev/null 2>&1; then
	dropbox start &
fi

if command -v xautolock >/dev/null 2>&1; then
	xautolock -time 60 -locker 'systemctl suspend' -detectsleep &
fi

if command -v nm-applet >/dev/null 2>&1; then
	nm-applet &
fi
