#!/bin/bash

DIRECTION='right'
DRYRUN=''
DUPLICATE=''

for arg in "$@"; do
	case $arg in
		-c|--copy )
			DUPLICATE='yes'
			;;
		-d|--dryrun|--dry-run )
			DRYRUN='yes'
			;;
		-l|--left )
			DIRECTION='left'
			;;
		-r|--right )
			DIRECTION='right'
			;;
		* )
			echo "Unknown argument: $arg"
			exit 1
			;;
	esac
done

connected=$(xrandr -q | grep -F ' connected' | awk '{ print $1 }')
num_connected=$(echo "$external" | wc -w)

if [ $num_connected -eq 1 ]; then
	# only internal display
	xrandr_args="--output $connected --auto --primary"
else
	declare -A outputs
	outputs[eDP-1]='--primary'
	outputs[HDMI-1]='--off'
	outputs[HDMI-2]='--off'
	outputs[DP-1]='--off'

	if echo "$connected" | grep -F 'DP-1-' > /dev/null; then
		# docked setup for work
		outputs[DP-1-2]="--${DIRECTION}-of eDP-1"
		outputs[DP-1-1]="--${DIRECTION}-of DP-1-2"
	else
		# home with external display, or projector
		for output in $connected; do
			if [ "$DUPLICATE" = 'yes' ] && [ -n "$first_output" ]; then
				outputs[$output]="--same-as $first_output"
			elif [ -n "$prev_output" ]; then
				outputs[$output]="--${DIRECTION}-of $prev_output"
			else
				outputs[$output]="--primary"
				first_output=$output
			fi
			prev_output=$output
		done
	fi
fi

XRANDR_ARGS=""

for output in "${!outputs[@]}"; do
	XRANDR_ARGS="$XRANDR_ARGS --output $output --auto ${outputs[$output]}"
done

if [ "$DRYRUN" = 'yes' ]; then
	echo xrandr $XRANDR_ARGS
	xrandr --dryrun $XRANDR_ARGS
else
	xrandr $XRANDR_ARGS

	# if screen size changed, need to re-set the desktop background
	if [ -x $HOME/.fehbg ]; then
		$HOME/.fehbg &
	fi
fi
