window:
  dynamic_padding: false
  padding:
    x: 7
    y: 3

font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: semibold
  size: 10.0
  offset:
    x: 0
    y: 6
  glyph_offset:
    x: 0
    y: 3

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#000000'
    foreground: '#c5c8c6'
    dim_foreground: '#828482'
    bright_foreground: '#eaeaea'
  cursor:
    cursor: '#657b83'
  normal:
    black:   '#111111'
    red:     '#ef5350'
    green:   '#43a047'
    yellow:  '#ffd54f'
    blue:    '#039be5'
    magenta: '#9575cd'
    cyan:    '#26a69a'
    white:   '#9aa5ab'
  bright:
    black:   '#555555'
    red:     '#ef9a9a'
    green:   '#81c784'
    yellow:  '#ffe2a7'
    blue:    '#81d4fa'
    magenta: '#b39ddb'
    cyan:    '#80cbc4'
    white:   '#ffffff'

cursor:
  style: Block

key_bindings:
  - { mods: Alt, key: C, action: Copy }
  - { mods: Alt, key: V, action: Paste, mode: ~vi }

  # font size
  - { mods: Alt, key: Subtract, action: DecreaseFontSize }
  - { mods: Alt, key: Equals,   action: IncreaseFontSize }
  - { mods: Alt, key: Key0,     action: ResetFontSize    }

  # search and other functionality
  - { mods: Control, key: F, action: SearchForward }

  # vi mode controls
  - { mods: Control, key: Space, action: ToggleViMode }
