#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
	*i*) ;;
	*) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# history size in memory and in file
HISTSIZE=1000
HISTFILESIZE=10000

# always limit man to 80 characters wide
export MANWIDTH=80

# set tab width
tabs 4 > /dev/null

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f /usr/share/bash-completion/bash_completion ]; then
		. /usr/share/bash-completion/bash_completion
	elif [ -f /etc/bash_completion ]; then
		. /etc/bash_completion
	fi
fi

# ls --color config with dircolors
export LS_COLORS='fi=0:di=1;34:ow=1;34:ln=33:ex=1;32:mi=0;31'

# self-explanatory
export EDITOR=vim

# Add $HOME/bin to $PATH if the directory exists and not already added
if [ -d $HOME/bin ] && [[ ! "$PATH" =~ "$HOME/bin" ]]; then
	PATH="$HOME/bin:$PATH"
fi



#	  /$$$$$$  /$$ /$$                                        
#	 /$$__  $$| $$|__/                                        
#	| $$  \ $$| $$ /$$  /$$$$$$   /$$$$$$$  /$$$$$$   /$$$$$$$
#	| $$$$$$$$| $$| $$ |____  $$ /$$_____/ /$$__  $$ /$$_____/
#	| $$__  $$| $$| $$  /$$$$$$$|  $$$$$$ | $$$$$$$$|  $$$$$$ 
#	| $$  | $$| $$| $$ /$$__  $$ \____  $$| $$_____/ \____  $$
#	| $$  | $$| $$| $$|  $$$$$$$ /$$$$$$$/|  $$$$$$$ /$$$$$$$/
#	|__/  |__/|__/|__/ \_______/|_______/  \_______/|_______/ 

# by default, most WMs opening a new terminal will make it start in ~ instead of
# the current terminal's PWD. this alias lets you open a new terminal in the PWD
function t {
	local args="";
	if [[ "$@" != "" ]]; then
		args="-e $@"
	fi

	if [[ "$(which i3-msg)" ]]; then
		# opening through i3 exec prevents weird/inconsistent ps trees
		args="-cd $PWD $args"
		i3-msg "exec x-terminal-emulator $args" &> /dev/null
	else
		# fork in a subshell to make the commands indepentent, and to suppress
		# all output
		( x-terminal-emulator $args & )
	fi
}

# note taking
_NOTES_DIR=~/Dropbox/notes
function n {
	if [[ ! "$1" ]]; then
		echo "Missing argument - usage: n <name>"
		return
	fi
	local count=$(nls $1 | wc -l)
	if [[ $count > 1 ]]; then
		nls $1
		return
	elif [[ $count == 0 ]]; then
		$EDITOR "${_NOTES_DIR}/$1.md"
	else
		$EDITOR "${_NOTES_DIR}/$(nls $1)"
	fi
}
function nls {
	pushd $_NOTES_DIR > /dev/null
	if [[ ! "$@" ]]; then
		ls *.md
	else
		ls -1 *.md | grep $@
	fi
	popd > /dev/null
}
function ns {
	if [[ $(which ag) ]]; then
		ag "$@" ${_NOTES_DIR}
	else
		grep -r "$@" ${_NOTES_DIR}
	fi
}

# enable colors for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ag doesn't have config files
alias ag="ag --color-path='0;37' --color-line-number='0;33' --color-match='1;34'"

# some ls aliases
alias ls='ls --time-style=long-iso --group-directories-first --color=auto -Fh'
alias l='ls -l'
alias la='l -A'
alias lt='l -tr'
alias l1='ls -1'

# file and dir stuff
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# make a directory and cd into it
function md {
	mkdir -p "$@" && cd $_;
}

# i3 shortcuts
alias i3exec='i3-msg exec'
alias i3lock='i3lock -c 000000'
alias i3rename='i3-msg rename workspace to'
alias i3mv='i3-msg move workspace to output'

# apache
alias a2r='sudo service apache2 reload'
alias a2rs='sudo service apache2 restart'
alias a2cs='\ls /etc/apache2/sites-enabled/'
alias a2em='sudo a2enmod'
alias a2dm='sudo a2dismod'
alias a2cfg='cd /etc/apache2 && ls'
alias a2log='cd /var/log/apache2 && ls -l'

# php
function ccp {
	composer create-project "$1" -s dev --prefer-dist "${*:2}";
}

# python
function avenv {
	if [ -f $PWD/.virtualenv/bin/activate ]; then
		source $PWD/.virtualenv/bin/activate
	elif [ -f $PWD/bin/activate ]; then
		source $PWD/bin/activate
	else
		echo "Couldn't find a virtualenv in cwd!"
	fi
}
function pyhelp {
	python -c 'help('"$@"')'
}
function py3help {
	python3 -c 'help('"$@"')'
}

# livestreamer
function s {
	livestreamer $1 ${2-high,720p,best}
}

# clear a file, then tail it
function cltail {
	cat /dev/null > "$1" && tail -f "$@"
}

# keyboard layout
function kb {
	setxkbmap -v -option compose:ralt -option caps:super $1 \
		&& xset r rate 175 35
}

# improved ps | grep alias
function psgrep {
	ps auxf | grep "$@" | grep -v grep;
}

# set a terminal's title
function termname {
	echo -ne "\033]0;$1\007"
}

# fetch a github pull request
function gh-fetch-pr {
	git fetch upstream "pull/$1/head:pr-$1"
}

# misc
alias cal='ncal -Mb3'
alias crlffix='for file in `find . -type f`; do dos2unix $file; done'
alias diff='git diff --no-index'
alias most-common='sort | uniq -c | sort -nr | head'
alias open='xdg-open'
alias pwgen-strong='pwgen -Bs'
alias pwgen-weak='pwgen -ABn'
alias tree='tree --dirsfirst'



#	 /$$$$$$$   /$$$$$$    /$$  
#	| $$__  $$ /$$__  $$ /$$$$  
#	| $$  \ $$| $$  \__/|_  $$  
#	| $$$$$$$/|  $$$$$$   | $$  
#	| $$____/  \____  $$  | $$  
#	| $$       /$$  \ $$  | $$  
#	| $$      |  $$$$$$/ /$$$$$$
#	|__/       \______/ |______/

# wrap in a function to allow local variables
_set_ps1() {
	local user_color='32' # green
	local host_color='32' # green
	local host_str='\h'

	if [ $USER = 'vagrant' ]; then
		user_color='34' # blue
	elif [ $USER = 'root' ]; then
		user_color='31' # red
	elif [ $USER != 'andreas' ]; then
		user_color='33' # yellow
	fi

	if [ -n "$SSH_CLIENT" ]; then
		host_str=$(hostname -f)
		if [[ $host_str == vagrant* ]]; then
			host_color='34' # blue
		else
			host_color='33' # yellow
		fi
	fi

	PS1='\[\033[01;'$user_color'm\]\u\[\033[0;37m\]@\[\033[01;'$host_color'm\]'$host_str'\[\033[00m\] \w'

	if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
		debian_chroot=$(cat /etc/debian_chroot)
	fi
	if [ ! -z "$debian_chroot" ]; then
		PS1="${debian_chroot:+($debian_chroot)} $PS1"
	fi

	if command -v __git_ps1 >/dev/null 2>&1; then
		# GIT_PS1_SHOWDIRTYSTATE=true
		# GIT_PS1_SHOWUNTRACKEDFILES=true
		GIT_PS1_SHOWUPSTREAM="auto"
		# GIT_PS1_SHOWCOLORHINTS=true
		PS1=$PS1'$(__git_ps1 "  \[\033[01;37m\]%s\[\033[00m\]")'
	fi

	PS1=$PS1'\n\[\033[0;37m\]\$\[\033[00m\] '
}

_set_ps1
