#!/bin/sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		. "$HOME/.bashrc"
	fi
fi

if [ -d "/sbin" ]; then
	PATH="/sbin:$PATH"
fi

if [ -d "/usr/sbin" ]; then
	PATH="/usr/sbin:$PATH"
fi

if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi

if [ -d $HOME/.local/bin ]; then
	PATH="$HOME/.local/bin:$PATH"
fi
