#!/bin/sh

if command -v killall >/dev/null 2>&1; then
    killall xautolock
elif pidof xautolock >/dev/null; then
    kill "$(pidof xautolock)"
fi

if acpi -b 2> /dev/null | grep -q Battery; then
    xautolock -time 60 -corners 000- -cornersize 30 -detectsleep -locker 'lockscreen --suspend' &
else
    xautolock -time 15 -locker 'lockscreen' &
fi
