#!/bin/sh

if command -v xset >/dev/null 2>&1; then
	# turn on/off system beep
	xset b off

	# mouse acceleration - accel ratio and threshold
	xset m 1/1 0

	# keyboard repeat - delay (ms) and characters per second
	xset r rate 175 35
fi

if command -v setxkbmap >/dev/null 2>&1; then
	# set xkbmap options
	setxkbmap -option compose:ralt -option caps:super
fi

# touchpad settings
if grep -Eiq 'synap|alps|etps' /proc/bus/input/devices && \
	command -v synclient >/dev/null 2>&1
then
	synclient AccelFactor=0
	synclient MinSpeed=1.25
	synclient MaxSpeed=3
	# tapping the touchpad sends a mouse button 1 event
	synclient TapButton1=1
fi

# feh sets the desktop background
if [ -x $HOME/.fehbg ]; then
	$HOME/.fehbg &
fi

if command -v xflux >/dev/null 2>&1; then
	xflux -l 58 -g 5 -k 2900 &
fi

if command -v compton >/dev/null 2>&1; then
	compton -b &
fi

if command -v dropbox >/dev/null 2>&1; then
	dropbox start &
fi

if command -v nm-applet >/dev/null 2>&1; then
	nm-applet &
fi

if command -v xfce4-power-manager >/dev/null 2>&1; then
	xfce4-power-manager &
elif command -v xautolock >/dev/null 2>&1; then
	xautolock -time 60 -detectsleep -locker '~/bin/lockscreen --suspend' &
fi

if command -v unclutter >/dev/null 2>&1; then
	unclutter -idle 3 -root &
fi

if command -v autocutsel >/dev/null 2>&1; then
	autocutsel &
fi
