#!/bin/sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# add paths to $PATH. these should be listed in order of
# least precedence first, highest precedence last
paths="
/sbin
/usr/sbin
$HOME/Library/Python/*/bin
$HOME/.cargo/bin
$HOME/.npm/bin
$HOME/.local/bin
$HOME/bin
"
for path in $paths; do
    if [ -d "$path" ] && [ ! -L "$path" ]; then
        PATH="$path:$PATH"
    fi
done
unset path paths

# bashrc doesn't execute itself
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# print active tmux sessions, if any
tmux ls 2>/dev/null
