#!/bin/sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# don't put duplicate lines or lines starting with space in the history.
HISTCONTROL=ignoreboth

# history size in memory
HISTSIZE=1000
# history size in history file
SAVEHIST=10000
HISTFILESIZE=10000
HISTFILE=~/.history

# always limit man to 80 characters wide
export MANWIDTH=80

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# ls --color config with dircolors
export LS_COLORS='fi=0:di=1;34:ow=1;34:ln=33:ex=1;32:mi=0;31'

# self-explanatory
export EDITOR=vim

# fix journalctl
export SYSTEMD_LESS='KMR +G'
# export SYSTEMD_LESS='FKMRX +G'

# alter $PATH
if [ -d "/sbin" ]; then
	PATH="/sbin:$PATH"
fi
if [ -d "/usr/sbin" ]; then
	PATH="/usr/sbin:$PATH"
fi
if [ -d "$HOME/bin" ]; then
	PATH="$HOME/bin:$PATH"
fi
if [ -d $HOME/.local/bin ]; then
	PATH="$HOME/.local/bin:$PATH"
fi

# If not running interactively, don't do anything more
case $- in
	*i*) ;;
	*) return;;
esac

# bashrc doesn't execute itself
if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		. "$HOME/.bashrc"
	fi
fi

# print active tmux sessions, if any
tmux ls 2>/dev/null
