#!/bin/sh

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
umask 022

# add paths to $PATH. these should be listed in order of
# least precedence first, highest precedence last
_paths="
	/sbin
	/usr/sbin
	$HOME/.cargo/bin
	$HOME/.local/bin
	$HOME/bin
"
for path in $_paths; do
	if [ -d "$path" ]; then
		PATH="$path:$PATH"
	fi
done

# bashrc doesn't execute itself
if [ -n "$BASH_VERSION" ]; then
	if [ -f "$HOME/.bashrc" ]; then
		. "$HOME/.bashrc"
	fi
fi

# print active tmux sessions, if any
tmux ls 2>/dev/null
