#!/usr/bin/env bash

# by default, most WMs opening a new terminal will make it start in ~ instead of
# the current terminal's PWD. this alias lets you open a new terminal in the PWD
function t {
	if [[ "$@" != "" ]]; then
		args="-e $@"
	fi

	if [[ "$(which i3-msg)" ]]; then
		# opening through i3-exec prevents weird/inconsistent ps trees
		args="-cd $PWD $args"
		i3-msg "exec x-terminal-emulator $args" &> /dev/null
	else
		# fork in a subshell to make the commands indepentent, and to suppress
		# all output
		( x-terminal-emulator $args & )
	fi
}

# note taking
_NOTES_DIR=~/Dropbox/notes
function n {
	if [[ ! "$1" ]]; then
		echo "Missing argument - usage: n <name>"
		return
	fi
	count=$(nls $1 | wc -l)
	if [[ $count > 1 ]]; then
		nls $1
		return
	elif [[ $count == 0 ]]; then
		$EDITOR "${_NOTES_DIR}/$1.md"
	else
		$EDITOR "${_NOTES_DIR}/$(nls $1)"
	fi
}
function nls {
	pushd $_NOTES_DIR > /dev/null
	if [[ ! "$@" ]]; then
		ls *.md
	else
		ls -1 *.md | grep $@
	fi
	popd > /dev/null
}
function ns {
	if [[ $(which ag) ]]; then
		ag "$@" ${_NOTES_DIR}
	else
		grep -r "$@" ${_NOTES_DIR}
	fi
}

# enable colors for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ag doesn't have config files
alias ag="ag --color-path='0;37' --color-line-number='0;33' --color-match='1;34'"

# some ls aliases
alias ls='ls --time-style=long-iso --group-directories-first --color=auto -Fh'
alias l='ls -l'
alias la='l -A'
alias lt='l -tr'
alias l1='ls -1'

# file and dir stuff
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias rm='rm -I --preserve-root'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# make a directory and cd into it
function md {
	mkdir -p "$@" && cd $_;
}

# i3 shortcuts
alias i3lock='i3lock -c 000000'
alias i3rename='i3-msg rename workspace to'
alias i3mv='i3-msg move workspace to output'

# server stuff
alias a2r='sudo service apache2 reload'
alias a2rs='sudo service apache2 restart'
alias a2cs='\ls /etc/apache2/sites-enabled/'
alias a2em='sudo a2enmod'
alias a2dm='sudo a2dismod'
alias a2cfg='cd /etc/apache2 && ls'
alias a2log='cd /var/log/apache2 && ls -l'

# php
function ccp {
	composer create-project "$1" -s dev --prefer-dist "${*:2}";
}

# python
function avenv {
	if [ -f $PWD/.virtualenv/bin/activate ]; then
		source $PWD/.virtualenv/bin/activate
	elif [ -f $PWD/bin/activate ]; then
		source $PWD/bin/activate
	else
		echo "Couldn't find a virtualenv in cwd!"
	fi
}
function pyhelp {
	python -c 'help('"$@"')'
}
function py3help {
	python3 -c 'help('"$@"')'
}

# livestreamer
function s {
	livestreamer $1 ${2-high,720p,best}
}

# clear a file, then tail it
function cltail {
	cat /dev/null > "$1" && tail -f "$@"
}

# keyboard layout
function kb {
	setxkbmap -v -option compose:ralt -option caps:super $1 && xset r rate 175 35
}

# improved ps | grep alias
function psgrep {
	ps auxf | grep "$@" | grep -v grep;
}

# set a terminal's title
function termname {
	echo -ne "\033]0;$1\007"
}

# fetch a github pull request
function gh-fetch-pr {
	git fetch upstream "pull/$1/head:pr-$1"
}

# misc
alias cal='ncal -Mb3'
alias crlffix='for file in `find . -type f`; do dos2unix $file; done'
alias most-common='sort | uniq -c | sort -nr | head'
alias open='xdg-open'
alias pwgen-strong='pwgen -Bs'
alias pwgen-weak='pwgen -ABn'
alias ss='sudo service'
alias tree='tree --dirsfirst'
