name: run-tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: koalaman/shellcheck-alpine:stable
    steps:
      - uses: actions/checkout@v2
      - run: ./shellcheck.sh
