name: run-tests

'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - container:
          image: koalaman/shellcheck:stable
          options: -v /__w/anlutro/dotfiles:/mnt:ro
        run: ./shellcheck.sh
